# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/rsa_cipher.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_rsa_cipher(object):
    def setupUi(self, rsa_cipher):
        rsa_cipher.setObjectName("rsa_cipher")
        rsa_cipher.resize(1128, 633)
        self.btn_encrypt = QtWidgets.QPushButton(rsa_cipher)
        self.btn_encrypt.setGeometry(QtCore.QRect(170, 470, 93, 28))
        self.btn_encrypt.setObjectName("btn_encrypt")
        self.label = QtWidgets.QLabel(rsa_cipher)
        self.label.setGeometry(QtCore.QRect(80, 130, 55, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(rsa_cipher)
        self.label_2.setGeometry(QtCore.QRect(500, 30, 91, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(rsa_cipher)
        self.label_3.setGeometry(QtCore.QRect(80, 280, 61, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(rsa_cipher)
        self.label_4.setGeometry(QtCore.QRect(590, 130, 61, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(rsa_cipher)
        self.label_5.setGeometry(QtCore.QRect(590, 280, 55, 16))
        self.label_5.setObjectName("label_5")
        self.txt_info = QtWidgets.QPlainTextEdit(rsa_cipher)
        self.txt_info.setGeometry(QtCore.QRect(590, 150, 521, 131))
        self.txt_info.setObjectName("txt_info")
        self.btn_decrypt = QtWidgets.QPushButton(rsa_cipher)
        self.btn_decrypt.setGeometry(QtCore.QRect(320, 470, 93, 28))
        self.btn_decrypt.setObjectName("btn_decrypt")
        self.btn_gen_keys = QtWidgets.QPushButton(rsa_cipher)
        self.btn_gen_keys.setGeometry(QtCore.QRect(520, 90, 101, 28))
        self.btn_gen_keys.setObjectName("btn_gen_keys")
        self.txt_sign = QtWidgets.QPlainTextEdit(rsa_cipher)
        self.txt_sign.setGeometry(QtCore.QRect(590, 300, 521, 131))
        self.txt_sign.setObjectName("txt_sign")
        self.txt_cipher_text = QtWidgets.QPlainTextEdit(rsa_cipher)
        self.txt_cipher_text.setGeometry(QtCore.QRect(70, 300, 471, 131))
        self.txt_cipher_text.setObjectName("txt_cipher_text")
        self.txt_plain_text = QtWidgets.QPlainTextEdit(rsa_cipher)
        self.txt_plain_text.setGeometry(QtCore.QRect(70, 150, 471, 131))
        self.txt_plain_text.setObjectName("txt_plain_text")
        self.btn_verify = QtWidgets.QPushButton(rsa_cipher)
        self.btn_verify.setGeometry(QtCore.QRect(890, 470, 93, 28))
        self.btn_verify.setObjectName("btn_verify")
        self.btn_sign = QtWidgets.QPushButton(rsa_cipher)
        self.btn_sign.setGeometry(QtCore.QRect(740, 470, 93, 28))
        self.btn_sign.setObjectName("btn_sign")

        self.retranslateUi(rsa_cipher)
        QtCore.QMetaObject.connectSlotsByName(rsa_cipher)

    def retranslateUi(self, rsa_cipher):
        _translate = QtCore.QCoreApplication.translate
        rsa_cipher.setWindowTitle(_translate("rsa_cipher", "Dialog"))
        self.btn_encrypt.setText(_translate("rsa_cipher", "Encrypt"))
        self.label.setText(_translate("rsa_cipher", "PlainText"))
        self.label_2.setText(_translate("rsa_cipher", "RSA_Cipher"))
        self.label_3.setText(_translate("rsa_cipher", "CipherText"))
        self.label_4.setText(_translate("rsa_cipher", "Infomation"))
        self.label_5.setText(_translate("rsa_cipher", "signture"))
        self.btn_decrypt.setText(_translate("rsa_cipher", "Decrypt"))
        self.btn_gen_keys.setText(_translate("rsa_cipher", "Genergate keys"))
        self.btn_verify.setText(_translate("rsa_cipher", "Vefity"))
        self.btn_sign.setText(_translate("rsa_cipher", "Sign"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    rsa_cipher = QtWidgets.QDialog()
    ui = Ui_rsa_cipher()
    ui.setupUi(rsa_cipher)
    rsa_cipher.show()
    sys.exit(app.exec_())
