# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/caeser.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(756, 722)
        self.txtplain = QtWidgets.QPlainTextEdit(Dialog)
        self.txtplain.setGeometry(QtCore.QRect(190, 120, 461, 87))
        self.txtplain.setObjectName("txtplain")
        self.txtkey = QtWidgets.QPlainTextEdit(Dialog)
        self.txtkey.setGeometry(QtCore.QRect(190, 240, 121, 87))
        self.txtkey.setObjectName("txtkey")
        self.txtcipher = QtWidgets.QPlainTextEdit(Dialog)
        self.txtcipher.setGeometry(QtCore.QRect(190, 360, 461, 87))
        self.txtcipher.setObjectName("txtcipher")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(80, 140, 55, 62))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(84, 390, 81, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(80, 270, 55, 27))
        self.label_3.setObjectName("label_3")
        self.btnen = QtWidgets.QPushButton(Dialog)
        self.btnen.setGeometry(QtCore.QRect(240, 530, 93, 28))
        self.btnen.setObjectName("btnen")
        self.btnde = QtWidgets.QPushButton(Dialog)
        self.btnde.setGeometry(QtCore.QRect(370, 530, 93, 28))
        self.btnde.setObjectName("btnde")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(340, 20, 51, 71))
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Plain Text"))
        self.label_2.setText(_translate("Dialog", "Cipher Text"))
        self.label_3.setText(_translate("Dialog", "Key"))
        self.btnen.setText(_translate("Dialog", "Encrypt"))
        self.btnde.setText(_translate("Dialog", "Decrypt"))
        self.label_4.setText(_translate("Dialog", "CAESER"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
